import Link from 'next/link';
const barbers=[
  ['Themba Mokoena','Senior Barber','Fades · Texture · Precision','https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=900&q=80'],
  ['Jayden Jacobs','Barber','Classic Cuts · Scissors · Styling','https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=900&q=80'],
  ['Sipho Dlamini','Barber','Beards · Tapers · Kids Cuts','https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=900&q=80']
];
export default function About(){return <>
  <div className="container page-hero"><span className="eyebrow">About the shop</span><h1>Old-school craft.<br/>Contemporary pace.</h1><p>Crown & Clip was imagined as the kind of barbershop people return to: good music, useful advice, sharp tools and a chair that never feels rushed.</p></div>
  <section className="section" style={{paddingTop:30}}><div className="container split"><div className="card story-card"><span className="eyebrow">Our standard</span><h3>The consultation matters as much as the cut.</h3><p>Every appointment starts with what you want, what will work with your hair, and how much maintenance you actually want to do at home. Then we execute the plan properly.</p><p>We keep our services focused so the quality stays consistent and the booking experience stays simple.</p></div><div className="gallery"><div className="shot tall"><img src="https://images.unsplash.com/photo-1622288432450-277d0fef5ed0?auto=format&fit=crop&w=1000&q=85" alt="Barber tools and workspace"/></div><div className="gallery-col"><div className="shot"><img src="https://images.unsplash.com/photo-1512690459411-b0fdcbb89e31?auto=format&fit=crop&w=900&q=85" alt="Barber chair and salon interior"/></div><div className="shot"><img src="https://images.unsplash.com/photo-1508385082359-f38ae991e8f9?auto=format&fit=crop&w=900&q=85" alt="Close-up of barber styling hair"/></div></div></div></div></section>
  <section className="section" style={{paddingTop:0}}><div className="container"><div className="section-head"><div><span className="eyebrow">Meet the team</span><h2>Three chairs. One standard.</h2></div></div><div className="grid barbers-grid">{barbers.map(([name,role,specialties,img])=><article className="card barber-card" key={name}><div className="barber-photo"><img src={img} alt={`${name}, ${role}`}/></div><div className="barber-body"><h3>{name}</h3><p>{role}</p><div className="tag-row">{specialties.split(' · ').map(x=><span className="tag" key={x}>{x}</span>)}</div></div></article>)}</div></div></section>
  <section className="section" style={{paddingTop:0}}><div className="container"><div className="cta-band"><div><h3>Pick your barber.</h3><p>Availability is checked live for the date and service you select.</p></div><Link className="btn" href="/booking" style={{borderColor:'#19140e'}}>Choose a time →</Link></div></div></section>
</>}
